     	<center>
<img alt="..."  width="400" height="200" class="img-circle" src="ms.png"/>
        </center>

<form name="login" method="post" action="">
<input type="hidden" name="get" value="nada" /> 
<table border="0" align="center" cellpadding="2" cellspacing="2" bgcolor="gray">
Reiniciar Contagem automatica<input type= 'radio' name="remotor" value="" />
<?php
$host = "localhost";
$usuario = "root";
$senha = "88255925";
$db = "mstelecom";

$mysqli = new mysqli($host, $usuario, $senha, $db);

if($mysqli->connect_errno)
  echo "Falha na conexão: (".$mysqli->connect_errno.") ".$mysqli->connect_error;


$con = mysqli_connect("localhost","root","88255925");
mysqli_select_db($con,"mstelecom");



$clientes = array(
'Adailson Vieira',
'Adelson da silva dias',
'Adiel carvalho',
'Adriana dias',
'Pedro Braga',
'Adriana silva santos',
'Ailmara',
'Alan baltazar',
'Alan Santos',
'Alessandra reis',
'Angela Santana',
'Avanir Soares de Oliveira',
'Carla do mercado',
'Cassia Carolina',
'Cecilia Maia',
'Cintia mulher de gazela',
'Clarice Santana',
'Claudia Ramos',
'Cleide Vania',
'Cleonice',
'Daniele Barbosa',
'Daniele Gonzaga',
'Patricia dos Santos Pereira',
'Giraia jaspion Jibam',
'Eduardo dos Santos Pereira',
'Bernardo Nascimento',
'Maiana Alves',
'Iraneide Alves',
'Maria de fatima de Jesus',
'Patricia Menezes',
'Sergio Carvalho de castro',
'Vanessa Rejane Araujo',
'Edinaldo de Jesus',
'Manuel Fagundes',
'Tatiane',
'Jane Meire Santos de souz',
'Deusdete dos santos silva',
'Danilo Menezes',
'Deise',
'Danilo de Souza Cunha',
'Debora pereira',
'Douglas emanuel pereira dos santos',
'Edineide Oliveira Ribeiro',
'Elquirio',
'Joaozinho',
'Wanderlei lopes',
'Carlos nascimento',
'Mamaco Santos',
'Jean alves santos',
'Jonas oliveira',
'Roque santana',
'Nelson moraes',
'Nelson moraes 2',
'Marines Souza ribeiro',
'Marines Souza ribeiroo',
'Jorge Pita',
'Rita de Rita',
'Evandro santos',
'Elizabete quiteria',
'Gabriel Santos',
'Gerson Gomes dos santos',
'Helena Amorim',
'Igor caudas',
'Isabela dos Santos Santiago',
'Jessica Gonzaga',
'Jose Augusto Guto',
'Jose milton Santos da Silva',
'Josias Santana',
'Josue Gomes de Jesus',
'Juliana Bomfim',
'Camila maria da conceisão',
'Lucas Felipe',
'Lucimara costa',
'Juliana santos',
'Mario Antonio da silva',
'Marize fernando',
'Michele sapucaia',
'ninja Cruz conceicao bahi',
'Robson trindade ',
'Nubia Regina Oliveira Souza',
'Suely braga',
'Val Braz',
'Valdeluce Nascimento',
'Zulene Santos',
'Anderson dos Santos correia',
'Taina Anita',
'Robson trindade Robsão',
'Adriana Fias dos Santos',
'Milena lopo',
'Elisangela santos maia',
'Marcos conceição',
'Areta carvalhal',
'Neinho martins',
'Rogerio Dos Reis Trindade',
'Antonio Davi Ribeiro Neto',
'Heloisa lima',
'Jeferson Manuel da silva',
'Eduardo dos santos coelho',
'Ana Patricia Santana bomfim',
'Gerson rodrigurs',
'Wendell Gomes',
'Antônio Carlos Bomfim',
'Paula Carolina',
'Neinho materiais de construcao',
'Ariel',
' Itamar fernandes lima',
'Regina lucia de Jesus',
'Nailan santos barbosa da silva',
'Maria Pinheiro',
'Carlitos Ferreira de Jesus filho',
'Joselene dos Santos Ramos',
'Jonilton silva de santana',
'luzia',
'Norma Silva Ribeiro',
'Yedo mesquita de freitas',
'Associação recreativa e cultural afoxé dança Bahia',
'Uilliams de Jesus',
'Lindnelson barbosa de souza',
'Koladek de ningeria',
'Cristiane Nascimento Mota',
'Nayara Conceição santos',
'Gaspar Tadeu de Jesus',
'Daniel de Oliveira Santana',
'Izabela Brito',
'Gilberto Barreto dos santos júnior',
'Claudio Vinicius Souza santos',
'Anderson da Hora dos Santos ',
'Rafaela Santos dos Santos',
'Rejane Souza ',
'Maria Joelma Santos Souza ',
'Antonio regino Gonçalves Amarantes',
'Sylvana cristine da cunha diniz',
'Zélia Souza Lima',
'Thales Aloísio Souza França',
'Maria José Cazuza dos Santos',
'Alival Correia peles',
'Morena que mora na cuva',
'Carlos Augusto Santos Vinagre',
'Marinalva Santos Vieira ',
'Murilo Adrian Pereira Ferreira',
'Aristóteles Pereira Santos Filho',
'Fabio vidal Gomes dos Santos ',
'Dilma Câmara Coelho',
'Alessandro Ferreira ',
'Rosângela Santos Athayde ',
'Gabriel Xavier de Santana ',
'Arlete de Jesus ',
'Samuel Barreto Pastor',
'Anofre dos Santos ',
'Danilo Rodrigues Nascimento',
'Ramsés Salvador dos Santos',
'Jorge Roberto franca de menezes',
'Leila Verena da Silva barreto',
'ANA PAULA DA SILVA',
'Paulo Sérgio pepe',
'Roberto Machado dos Santos',
'Dasiza sacramento ribeiro',
'Arlindo de Araújo Venas',
'Angelina Lucia rodrigues da cruz',
'Railsa Dias de Souza',
'Patrícia Martins roda lisboa',
'Giane costa cunha',
'Michele pereira',
'José neto cardoso santos',
'Verônica Aparecida Rodrigues calado',
'Junior Souza trabalhador',
'Fabio Silva',
'José Augusto de Jesus Sousa',
'José Hamilton Rosa pimentel',
'Isadora Bordoni ',
'Daniel Santos Teixeira ',
'Tânia Damiana Vitoria benevides',
'Daniel Gomes',
'Manoel Martins da Silva',
'Aline Bezerra da Silva ',
'maria de fatma da conceicao',
'Rita de Cassia da Conceição ',
'JUBIRA SANTOS',
'Diego Riela',
'Vital Coutinho de Santana',
'Luine de Oliveira da gama Alves',
'Josenita ramos dos santos ',
'Eneidison da SilvaFerreira',
'Tiago de Jesus dos Santos',
'Giliarde ribeiro de lima',
'Luiz Gonzaga Alves de jesus ',
'Jean Galvao',
'Vera Lucia Silva de Alburqueque',
'Rafael Santos de Melo',
'Erica pereira dos Santos',
'Ivane Brito Magalhães',
'Rebeca dos Santos Silva',
'Augusto sousa',
'Lázaro do Bonfim sacramento Miranda júnior ',
'Sorveteria Nazaré',
'Grasiele dos santos ferreira',
'Sheila Flávia Vieira Castro',
'Joilson de almeida pereira',
'Juciara nascimento dos santos',
'Luciano de Jesus Souza Filho',
'Erika dos Santos Machado',
'Tarso Guimarães Rosemberg',
'Amália Cristina Santos',
'Larissa da conceição',
'Aliomilson silva sena',
'Geovanna Martins Pereira Brotas ',
'Andrea Silva dos Santos',
'Elisângela Lima da Silva',
'Luzia cassia Jesus dos anjos',
'Igor de Jesus Caudas ',
'Lucas Figueiredo Gomes',
'Jacó dos Santos Brito',
'Tatiana da Cruz Oliveira Sena',
'Ivanilton Santana da silva',
'Raimunda da Conceição Gosmes',
'Valdizia_Andrade Silva Cruz',
'Rosimeire Pires Dias',
'Sávio Porto Silva',
'Belivar Santos Carneiro',
'Kelvin Correia da Silva',
'Arlindo nascimento silva ',
'Tamires Silva Lima',
'Bruno Nascimento Silva',
'Patrícia Silva Alves',
'Jackson de Jesus Santos',
'Caita Sirlene Pereira Oliveira',
'Celino Araujo Santos',
'Ítalo Cardoso da Silva',
'Felipe Mateus Mendes Barbosa',
'Maria das candeias Ântunes da silva',
'Luiz carlos de araujo',
'Sergio Ferreira de Santana ',
'Isadora Bastos de Souza Carneiro',
'Rosani dos Santos Silva',
'Vanderliz Pereira de Oliveira',
'Analice Santos da Conceição',
'Maurina Conceição de Jesus ',
'Aline souza teodoro',
'Nilton da cunha santos',
'Sirlei Santana dos Santos',
'Denise Silva dos Santos ',
'Reinaldo Sousa Roseira',
'Rodrigo. Hora souza',
'Danrley Silva matos',
'Caroline alessandra de jesus santos',
'Danilo Soares Xavier',
'José Edvaldo Jesus do carmo',
'Simone souza almeida',
'Maria de lourdes bezerra da Silva',
'Edilene Alves de Jesus',
'Fabrício Santana de Oliveira Torres',
'Crislaine Silva Oliveira',
'Bruna dos Santos Cardoso',
'Jessica Brandão Neri da Silva',
'Diego Sena',
'Rosilene Souza Conceição',
'Horbervan cidral do Bonfim',
'Telma Maria Santos',
'Carlos augusto costa de alcantara',
'Marcelino da cruz junior',
'Lorena de Souza Santos',
'Elisângela da Silva Barbosa',
'Rosimeire Bonfim',
'Sandra Asfora e Silva',
'Jucelino Caldas dos Santos',
'Jose raimundo costa garcia',
'Beatriz Brito Menezes Pino Toucedo',
'Lucas Petitinga',
'Rosana Santana de Jesus',
'Wilson raimundo silva Nascimento',
'Vanilda dos santos lima',
'Gustavo Bomfim dos Santos',
'Janusia Rosa de Sousa passos',
'Aline Grego',
'Tayane Souza dos Santos',
'Taiane souza ramos',
'Jirlane simas santana',
'Andrea carla andrade dos santos',
'Macio sales de souza',
'Carine Santana Pacheco de Ameida',
'Laissa dos Santos Barbosa',
'Marli santos fernandes',
'Roberval mendes de jesus',
'Shelze Santana de almeida',
'Givaldo santos de oliveira',
'Vanessa Cidral Bonfim',
'Andreia costa da Purificação',
'Marizete Rodrigues da Silva santos',
'Nanci Santos Ribeiro Santana',
'Ednaldo de Jesus',
'Paulo Sérgio Paraguassu',
'Daniel Soares dos Santos ',
'Sônia Maria Dias da Paixão dos Santos ',
'Crislaine Pereira de Oliveira cris',
'Andrea de Jesus Castro ',
'Jamily de Souza silva',
'Daniel dos Santos Oliveira',
'Rita de Cássia Silva de Jesus',
'Raphael Lopes Da Silva ',
'Erica de Jesus Figueiredo',
'Jessica Talita Garcia Pires',
'Valter de Jesus nunes',
'Rosane Khoury Hitti',
'Renilda da Silva Oliveira',
'Wilson Silva Fernandes',
'Fabiana Santos da Gama',
'Jecinete Santos Souza ',
'Rubens Silva serafim de Almeida ',
'Gilmar silva teles',
'Anderson de Carvalho Franco',
'Andreia Munis dos Santos ',
'Maria da glória Andrade Barbosa',
'Leila Oliveira da silva',
'Rosangela Silva Dos Santos ',
'Jailson dos Santos Almeida',
'Joilson de Jesus Dias',
'Virgínia ferreira Almeida',
'Iury santos costa',
'Marilene Silva Correia França',
'Alex vitor brito silva',
'Fábio Gomes da Silva',
'Florêncio farias de solza',
'Robson luiz alves Teixeira',
'Luana Oliveira da Silva',
'Carmelita rodrigues de queiroz',
'Mateus da silva santos',
'Raniele Andrade do Bomfim Souza',
'Simone Barbara Araujo Magalhães Antunes',
'Joice Menezes Porto',
'Naira de miranda pereira',
'Eutália da Silva Oliveira ',
'Beatriz Cardoso Brandão da Silva',
'Célia evangelista dos santos',
'Sonia Silva Souza',
'Maria das graças Silva castro',
'Nailton sousa fe jesus',
'Fernando Almeida da silva',
'Larissa Lima de Souza',
'Gilmario da conceição',
'Jéssica Caroline Silva das dores',
'Cleonice dos santos',
'Amanda Santa Rosa Cruz',
'Sandro Luna belas',
'Ana Claudia Ferreira da Paixão',
'Nilton da Hora Alves',
'Natana Medeiros Alves',
'Zildirlene Neves Batista Santos ',
'Arthur Conceição dos santos',
'MOYSES FERREIRA DA SILVA',
'Cintia Góes Borges',
'Ricardo Santos Athayde ',
'Ricardo Campos Brito',
'Bruno José Carvalho silva',
'Valnei Prazeres Dos santos',
'Islane Santana',
'Marcia oliveira santos',
'Helen Brito Menezes Pino Toucdo',
'Marcos da Cruz borges',
'Iuri Deraldo Oliveira',
'Renilde Brito da Silva',
'Kelvin Rozario de Jesus ',
'Raquel Conceição dos Santos ',
'Mona Figueiredo Martins',
'Camila dos santos evangelista ',
'Danilo Santos Bomfim ',
'Francisco José sales Reis',
'Caique Barbosa Lopes',
'Valdirene Cavalcante dos Santos',
'Luciana Barreto de Sousa',
'Dilson santos de oliveira',
'Carolina Guimarães de Souza',
'TAÃ MUNIQUE DIAS PELETEIRO',
'Lourival José de Oliveira Filho',
'Edmar Almeida dos Santos',
'Gustavo Santos da Silva ',
'ANA MIRIAN ROCHA MORAIS',
'Carmelha Neres da boa morte',
'Monique Vieira de Oliveira',
'Helen Brito Menezes pino toucedo',
'Jucilene de jesus Santos',
'Douglas da silva meneses da costa',
'Sonia maria dos santos vieira',
'Gabriel de jesus',
'Romario Santos Bispo',
'Graziele Matos Reges ',
'Elisa leite elias da Cruz ',

);

$sql="SELECT * FROM conf where id_usuario = '138'";
$res=mysqli_query($con,$sql);
while($vreg=mysqli_fetch_row($res)){
$id_servserv = $vreg[7];
}
$id_servserv = $id_servserv + 1;
$sql="UPDATE conf SET servidores = '$id_servserv' where id_usuario = '138'";
$res=mysqli_query($con,$sql);

if(isset($_POST["remotor"])){
$t=$_POST["remotor"];

$id_servserv = $id_servserv + 1;
$sql="UPDATE conf SET servidores = '1' where id_usuario = '138'";
$res=mysqli_query($con,$sql);
echo '<script type="text/javascript"> 
var urlAtual = window.location.href;
window.location.href=urlAtual;
</script>';
}



echo'<br><center>
<form name="login" method="post" action="">
<input type="hidden" name="get" value="nada" />
<input type="submit" class="form-control" name="Sortear" value="SORTEAR" /> </table><form></center>';




$num=rand(1,386);
echo "<center><h2> Sorteio MSTELECOM 4º prêmio! </h2>";
echo $id_servserv . '</center><br>';
echo '<h1><center> Cliente da sorte:<br> ';
$id_servserv;
if($id_servserv == 50){echo '<font color=red><h1>' ;}
 echo $clientes[$num];
$id_servserv;
if($id_servserv == 50){echo '</h1></font> <h2>Parabêns você acaba de ganhar uma mensalidade grátis!</h2>' ;}

if($id_servserv <= 49) 

{echo '<script type="text/javascript"> 
var urlAtual = window.location.href;
window.location.href=urlAtual;
</script>';}
?>